language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: eFOv2FRrZ02qqAU6Zc9WQcDkie6cff2IjtWcaAoOorjXz25O+Z74n+cBza9mMsKlrF4otiPyZ09RMWWpVgtWI6a4UDlL85I0LFIJzvnUJLuH0GhYYDL3VjuwxgrdwQUXEibmRLh245/5dSPESihqbwZVQI9uww6+VPbMDGM/raY=
  app: afternoon-journey-68885
  on:
    repo: heroku/node-js-getting-started
